"""Interface for SGEO Database implementations."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class CityInfo(Protocol):
    """City information structure."""
    city_code: int
    city_name: str
    state_code: str


@runtime_checkable
class ISGEODatabase(Protocol):
    """Abstract interface for SGEO database operations.

    Note: The benchmark_db_sync expects synchronous methods (no async/await).
    Use with asyncio.get_event_loop().run_until_complete() for initialize/close.
    """

    def initialize(self) -> None: ...
    def close(self) -> None: ...
    def get_city_info(self, city_name: str, state_code: str) -> tuple | None: ...
    def is_multi_street_cep(self, cep: str) -> bool: ...
    def fetch_address_by_cep(self, zip_code: str, limit: int = 10) -> list[tuple]: ...
    def fetch_address_by_street_id(self, street_id: int) -> list[tuple]: ...
    def fetch_geo_location(self, street_id: int, number: int, limit: int = 3) -> list[tuple]: ...
    def fetch_street_by_query_ids(self, query_ids: list[int], city_code: int) -> list[str]: ...
    def fetch_address_by_street_names(self, street_names: list[str], city_code: int) -> list[tuple]: ...
    def fetch_query_ids(self, city_code: int) -> list[int]: ...