FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    curl autoconf automake libtool pkg-config \
    build-essential git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN git clone https://github.com/openvenues/libpostal
WORKDIR /opt/libpostal
RUN ./bootstrap.sh
RUN ./configure --datadir=/usr/share/libpostal
RUN make -j4
RUN make install
RUN ldconfig

RUN pip install postal

WORKDIR /app
COPY . /app
ENV PYTHONPATH="."

CMD ["python", "benchmarks/benchmark_libpostal.py"]
